job:
  - 
    name: Iris Dataset 1
    image: 'qa:latest'
    runtime:
      shm-size: 8G
      cpus: 6
      memory: 10G
      pull: Yes
    flags:
      mode: iris
      input: data/iris
  
  - 
    name: Face Dataset 2
    image: 'qa'
    runtime:
      shm-size: 8G
      cpus: 6
      memory: 10G
      pull: No
    flags:
      mode: face
      input: data/face
      filename: '*FACE*'
  
  - 
    name: Fingerprint Dataset 1
    image: 'qa:v1.1.0'
    runtime:
      shm-size: 8G
      cpus: 6
      memory: 10G
    flags:
      mode: finger
      input: data/finger
      attributes: 'NFIQ2'
      query: 'NFIQ2>40'
